### ISSUE TITLE
'create-goji-app' cannot create an app

### ISSUE THREAD

**Issue by tgioer** [airbnb/goji-js#122]
PS D:\Projects\TaroifyProjects> yarn create goji-app my-goji-app
yarn create v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-goji-app@0.11.4" with binaries:
      - create-goji-app
[#################################################] 49/49Success! Created my-goji-app at D:\Projects\TaroifyProjects\my-goji-app
Inside that directory, you can run several commands:

  yarn start [target]
    Start Goji in development mode

  yarn build [target]
    Start Goji in production mode

The [target] could be one of wechat / baidu / alipay / toutiao / qq / toutiao

We suggest that you begin by typing:

   cd my-goji-app
   yarn
Done in 5.28s.
PS D:\Projects\TaroifyProjects> cd my-goji-app
cd : 找不到路径“D:\Projects\TaroifyProjects\my-goji-app”，因为该路径不存在。
所在位置 行:1 字符: 1
+ cd my-goji-app
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Projects\TaroifyProjects\my-goji-app:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
 
PS D:\Projects\TaroifyProjects>

**Comment by malash** [comment]
Hello @tgioer , thanks for your reporting.

I'v confirmed this bug on Windows 10. I fixed the bug in https://github.com/airbnb/goji-js/pull/123 and added CI to ensure it works on latest Windows system.

However, I recommend you to use Linux/Unix environments, like [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) / macOS / Ubuntu, to create and develop a GojiJS project. You'll have a more comfortable development experience.
