### ISSUE TITLE
Cannot use <include> in <template> on Alipay

### ISSUE THREAD

**Issue by malash** [airbnb/goji-js#140]
# Description

When [lib v2](https://opendocs.alipay.com/mini/framework/lib-upgrade-v2) being enabled, `<include>` in `<template>` cause compilation error on Alipay dev tool.

![image](https://user-images.githubusercontent.com/1812118/146043570-3ef694b7-b079-4afa-98e8-37361cf25bea.png)

# Reproduct link

[lib2-issue.zip](https://github.com/airbnb/goji-js/files/7713382/lib2-issue.zip)

# Reproduct steps

1. Unzip the file
2. Open in Alipay dev tool 2.7.2 

# Impact

GojiJS use this feature to import `leaf-components` in `components` and fails to run on latest Alipay.

# Temporary solution

Replace `<include>` with `src`'s content.

# Platforms

- [ ] WeChat
- [ ] Baidu ( including Xiaohongshu )
- [ ] QQ
- [x] Alipay
- [ ] Toutiao
- [ ] KuaiApp

**Comment by malash** [comment]
Reopen because `leaf-components` still not work with lib v2.

**Comment by Veercodeprog** [comment]
@malash is this open?
i can try fixing

**Comment by malash** [comment]
I have reported this issue to official forum but got no useful info
https://open.alipay.com/portal/forum/post/65101062

This problem becomes urgent and blocks Alipay miniapp development because [Alipay force to use Lib v2](https://opendocs.alipay.com/mini/framework/lib-upgrade-v2) since rencently.
