### ISSUE TITLE
[question] Is this repository still actively maintained?

### ISSUE THREAD

**Issue by yxiZo** [airbnb/goji-js#248]
Hello, I would like to know whether this repo is still being maintained. I am currently starting a mini program application and am very interested in trying it out for development. btw,  thank you for your work.

**Comment by malash** [comment]
Thank you for your supporting. The answer is yes. The GojiJS project is still under maintenance. 
The [official documentations](https://goji.js.org/docs/get-started/introduction) might be helpful if you are the first time developing on GojiJS. Also, if you find any problem you create an issue, a more detailed description will help us solve the problem faster.
