### ISSUE TITLE
提问：如何复用原生组件？混合开发？和第三方组件？

### ISSUE THREAD

**Issue by iheyunfei** [airbnb/goji-js#31]
# 如何复用原生组件？

这个应用场景主要有以下3点：
- 内部小程序的特殊组件
我在某大厂实习，有些内部特殊原生组件gojijs无法适配的，这点可能对gojijs有点苛求了，不过重点在于我没找到对小程序原生组件进行包装的方式，比如说：将 `<view />` 包装成 `<MyView />`  在 gojijs 中使用的能力
- 如何在小程序更新后，不需要等待goji-js更新就能用上最新的组件
同上，当小程序更新了一个新的原生组件后，现有情况下，似乎只能等待 gojijs 对相关组件进行适配更新后才能够在 gojijs 内部使用

# 混合开发？解决性能敏感页面
一般来讲大部分情况下都不会碰到强求性能的情况，但是总有些情况可能是仅仅在 React 这一层做优化是无法满足的，只能直接上原生页面，这种情况可能很少，但是一旦出现就绕不过去，所以对这点也很好奇gojijs的解决方式

# 复用第三方组件？

这个同理，大部分第三方组件，特别是 ui 组件，都是通过小程序原生的写法写的，我没有找到很好的办法简单写一下包裹层就直接复用到 gojijs

ps：对这个项目很看好

**Comment by Ziyu-Chen** [comment]
同学可以问一下微信小程序的api（https://developers.weixin.qq.com/miniprogram/dev/api/）在goji.js应该怎么用吗？
先谢谢你了！

**Comment by iheyunfei** [comment]
gojijs 的代码最终还是跑在小程序运行环境下的，这种挂载全局环境上的 api 直接调用 `wx.canIUse()` 就可以了，这里 gojijs 应该是出于某些考虑没有把微信相关的类型定义引进来，所以会有未定义相关的错误提示。

你可以看下这个仓库 https://github.com/wechat-miniprogram/api-typings ，安装后就会出现正确的类型提示了

> 同学可以问一下微信小程序的api（[https://developers.weixin.qq.com/miniprogram/dev/api/]）在goji.js应该怎么用吗？
> 我在官方文档里完全没找到...
> 先谢谢你了！

**Comment by Ziyu-Chen** [comment]
好的 谢谢你！

> gojijs 的代码最终还是跑在小程序运行环境下的，这种挂载全局环境上的 api 直接调用 `wx.canIUse()` 就可以了，这里 gojijs 应该是出于某些考虑没有把微信相关的类型定义引进来，所以会有未定义相关的错误提示。
> 
> 你可以看下这个仓库 https://github.com/wechat-miniprogram/api-typings ，安装后就会出现正确的类型提示了
> 
> > 同学可以问一下微信小程序的api（[https://developers.weixin.qq.com/miniprogram/dev/api/]）在goji.js应该怎么用吗？
> > 我在官方文档里完全没找到...
> > 先谢谢你了！

**Comment by malash** [comment]
@iheyunfei 你好。

首先感谢你对项目的支持，并帮助回答了 @Ziyu-Chen 的问题。你的回答是基本正确的。目前 GojiJS 文档缺少对于 `wx` 下API的使用说明，我接下来会对文档进行完善。

补充一点，在 GojiJS 的 CLI 中其实还做了一件事情，就是通过编译手段将全局变量 `wx` 映射到了不同平台，例如在百度小程序里 `wx.canIUse` 就会变成 `swan.canIUse`。因此在编写代码时，对于大部分定义相同的 API 只要一份代码即可兼容多个平台。

其次，对于原生组件——如 `view` 、`canvas` 这些，在 `@goji/core` 包中都是以 Pascal 大小写的形式导出的，例如 `view` 对应 `View`，使用的时候可以写作 `<View></View>`。完整的例子可以参见[这里](https://goji.js.org/docs/zh-CN/introduction#%E4%BE%8B%E5%AD%90)和[这里](https://goji.js.org/docs/zh-CN/page#%E9%A1%B5%E9%9D%A2%E6%96%87%E4%BB%B6)。对于你提到的某些特殊原生组件 GojiJS “可能”无法适配，据我所知是有这样的情况的（例如 input、swiper），但这些兼容性问题其实 GojiJS 已经做了适配，你可以再尝试以下，如果遇到不兼容情况欢迎提一个 Issue，我会进行适配。

但是，很显然 GojiJS 作为一个下游库，它同时具有几个上游依赖，一是各个小程序平台的框架、组件、API，二是 React （准确讲是 React Core 和 React Reconciler）。上游库的变更必然会影响到下游，GojiJS 需要修改代码进行适配其实是一件很正常的事情，我也很欢迎大家提 Issue 或者 PR 贡献自己的力量。

然后，对于混合开发这个问题，第三方组件支持只是其中一部分。总的来讲，混合开发大概包含以下几种情况：

1. 在原生小程序中使用 GojiJS 组件和页面
2. 在 GojiJS 小程序中使用原生组件和页面

这个问题比较复杂，我分开来讲。

“1. 在原生小程序中使用 GojiJS 组件和页面”，GojiJS 本身是跨平台的框架，但并不意味着开发者必须编写跨平台的代码，换句话讲开发者可以使用 GojiJS 只开发某一个平台的小程序代码，例如在 Airbnb 最初只有一个微信小程序，通过不断重构替代掉了其中大部分组件和页面，在这个过程中是存在一个中间状态的，即整体是一个微信小程序，但混合了部分 GojiJS 代码。我们在这方面是有一些探索的，但并不完美，在打包流程、代码迁移等方面并没有找到很普适的解决方法；况且这只是一个中间状态，最终是肯定会被抛弃的，因此并没有计划对这部分再投入精力。

“2. 在 GojiJS 小程序中使用原生组件和页面”，有几种可能会遇到这个需求：

一是如你所说一些已经实现好的第三方组件是以原生方式实现的，希望在 GojiJS 里复用。其实这里有一个很本质的问题就是这些组件并不是跨平台的，它们的引入会导致小程序被限制到特定的平台，失去了跨平台的 GojiJS 固然可用，但也失去了它的优势。根据我的经验，如果希望开发一个 GojiJS 应用，建议先从组件库开始。例如在 Airbnb 公司内部有一个闭源的 [DLS](https://airbnb.design/tag/dls/) 组件库，它由我司的设计团队和工程团队共同完成，有 Web、Android、iOS等各个平台的实现。在我们将小程序迁移到 GojiJS 时，我所在的小程序平台团队首先对整个组件库进行了实现，然后才进行业务代码的重构，俗话说“工欲善其事，必先利其器”，只有打好了组件库的基础才能更好更快的进行业务迁移。当然了，对于个人开发者或者中小型公司，选择一套开源组件库作为基础可能也是不错的选择，由于技术原因 GojiJS 目前无法直接利用已有的小程序原生组件库，必须重新实现一次。我希望 GojiJS 接下来可以对 WeUI 等常见组件库进行支持，以方便更多的开发者，当然我也希望可以借助社区的力量，共同丰富 GojiJS 的生态。

二是在某些页面或组件中存在性能上的问题，必须考虑使用原生开发。我认同你的说法“这种情况可能很少，但是一旦出现就绕不过去”。框架各有所长，GojiJS 更容易跨平台的同时，也带来了性能上的损失，特别是逐帧动画、事件监听等需要从渲染层到 React 交互的地方，会遇到一些性能问题。这个问题可能需要较长的时间去寻找解决方法，使用混合开发原生代码也许是一个可行的方案；现阶段 Airbnb 在将小程序迁移到 GojiJS 的同时，对 UI 交互进行了一定的调整，通过业务上的修改避免触发性能的问题，也是可以参考的方法。

三是一些特定平台的功能需要调用原生组件和页面，例如微信小程序中的“插件（plugin）”，百度智能小程序的“dynamicLib”，这些需求是合理的并且会在接下来的版本中尝试进行支持。GojiJS 的发展是一步步的，如果把所有小程序平台支持的功能想像成集合，那么 GojiJS 目前支持的基本上都属于功能的“交集”，这保证了 GojiJS 编写出的代码能够跨平台运行；而在接下来 GojiJS 会努力去支持功能 “并集”，既保证兼容性的同时又能支持不同平台独特的功能，最终成为一个健壮的小程序框架。

最后感谢两位对项目的支持，有更多问题和建议欢迎提 Issue 给我们 😄

**Comment by iheyunfei** [comment]
@malash 有任何办法取消使用 css module 吗？ 我在尝试适配一个原生小程序编写的 ui 库到 goji，过程中遇到一些问题。

## ui 库也被绑定了 css module 方案
因为现在第三方 ui 库 的 css 文件 一样要走 create-goji-js 中 webpack 的 loader ，ui 库的编写者没法选择是否采用 css module 方案。 虽然总是可以通过使用 `:global {}` 来达到相同的效果，但这就使得适配过程变得麻烦了许多，如果原来 ui 是用 css 编写还好，只需要每一个文件都加上 `:global {}` 还比较容易，但是大部分 ui 库为了开发方便都是使用的 less 或 sass 编写，而 less 和 sass 本身与 css module 配合并不是很好，我尝试在 less 内使用 `:global {}` 语句编译到 css 然后手动适配，但是编译后的 css 代码会报一些很诡异的语法错误。

我个人写项目也是默认使用 css module ，但我觉得把 css module 当作唯一方案可能不利于开发。

### 建议

这是我想出来的解决方案

- 或将 css module 的模式定义为可配置项，可以在 goji.config.js 里进行配置相应的 mode。
- 或将 css module 的模式改为 auto 通过文件命名区分是否启用 css module

适配时将模版改成 jsx 无可厚非，但是如果样式文件没法简单 copy-paste 使用的话，适配就变得比较麻烦了。

**Comment by malash** [comment]
@iheyunfei 这是个很好的问题，值得讨论。

不过呢，提一个建议，大家可以给不同的问题创建不同的 Issue，避免 Issue “跑题”，也方便后来的开发者更容易找的想要的答案。

关于CSS Moduke的疑问，我帮你创建了一个新的 Issue 在 [这里](https://github.com/airbnb/goji-js/issues/32)，我会在那里解答一下。
