### ISSUE TITLE
Consider to support CSS-in-JS libraries like linaria

### ISSUE THREAD

**Issue by malash** [airbnb/goji-js#32]
Original thread from https://github.com/airbnb/goji-js/issues/31#issuecomment-707002977 @iheyunfei

> @malash 有任何办法取消使用 css module 吗？ 我在尝试适配一个原生小程序编写的 ui 库到 goji，过程中遇到一些问题。
> ui 库也被绑定了 css module 方案
因为现在第三方 ui 库 的 css 文件 一样要走 create-goji-js 中 webpack 的 loader ，ui 库的编写者没法选择是否采用 css module 方案。 虽然总是可以通过使用 :global {} 来达到相同的效果，但这就使得适配过程变得麻烦了许多，如果原来 ui 是用 css 编写还好，只需要每一个文件都加上 :global {} 还比较容易，但是大部分 ui 库为了开发方便都是使用的 less 或 sass 编写，而 less 和 sass 本身与 css module 配合并不是很好，我尝试在 less 内使用 :global {} 语句编译到 css 然后手动适配，但是编译后的 css 代码会报一些很诡异的语法错误。
> 我个人写项目也是默认使用 css module ，但我觉得把 css module 当作唯一方案可能不利于开发。
> 建议
> 这是我想出来的解决方案
> 或将 css module 的模式定义为可配置项，可以在 goji.config.js 里进行配置相应的 mode。
> 或将 css module 的模式改为 auto 通过文件命名区分是否启用 css module
适配时将模版改成 jsx 无可厚非，但是如果样式文件没法简单 copy-paste 使用的话，适配就变得比较麻烦了。

**Comment by malash** [comment]
感谢 @iheyunfei 的提问，诚如你所说目前的 GojiJS 确实限制了只能使用 CSS Module 和PostCSS 作为 CSS 打包方案，这一选择是“可能不利于开发”的。因为这是根据小程序技术特点妥协后的选择，算不上完美，有很大的改进空间。

那么有没有可能在 GojiJS 里使用其他 CSS 打包方案呢？在回答这个问题之前，我们需要首先看一下为什么现阶段 GojiJS 使用了 CSS Module。

# 小程序技术特点

在原生小程序中（这里以微信为例），根据官方的文档一般推荐开发者使用 `.wxss` 文件编写 CSS 样式，然后在 `.wxml` 文件中通过 `class` 属性为节点绑定样式。这种框架设计很好的保证了结构与样式的分离，在很长一段时间内这也是前端常用的做法，即使是 CSS Module 这样的组件化方案，也是采用了 `className` 进行样式绑定的。

不过，这些的绑定也会带来一些问题，那就是 CSS 的灵活性比较差，例如我们希望一段文字以红、黄、蓝三种颜色显示，我们可以使用变量实现 `class="color-{{myColor}}"` ，并分别编写 `.color-red` / `.color-yellow` / `.color-blue` 三段 CSS 样式。

但是，如果变量的枚举值很多，或者这个变量可以是任意色值，那么这个方案的灵活性就不够用了。因此对于这种情况，开发者需要使用 `style` 属性，如 `style="color: {{muyColor}}"`。对于更加复杂的情况，开发者可能会直接使用 JavaScript 拼接 CSS 样式，作为一个整体使用，如 `style="{{myStyle}}"`。

# CSS Module

那么，如果在 GojiJS 里使用 CSS ，是如何处理的呢？

由于 GojiJS 需要保持足够的灵活性，因此所有的 DOM 节点信息是通过 setData 传递到渲染层的。对于下面这一段代码：

```tsx
<View style={{ color: 'red', fontSize: '20rpx' }}>
```

会被处理为 `setData({ style: 'color: red; font-size: 20rpx' })`，最终插入到 `.wxml` 文件进行渲染。

可以发现，相比于原生小程序，在GojiJS 如果开发者大量使用 `style` 编写 CSS 样式，那么 `setData` 的传输量会大量增加，进而带来严重的性能问题。

那么，有什么合适的解决方法呢？是有的，目前 GojiJS 选择使用 CSS Module，就在很大程度上避免了传递 CSS 带来的性能问题。

在 CSS Module 中，大部分静态的（没有变量的）样式编写在 `.css` 文件，这些文件会直接编译为 `.wxss` 文件，在 `setData` 中只需要传递少量哈希过的 `class` 即可。当然，在一些对灵活性要求比较高的地方，开发者依然可以使用 `style` 编写代码。

CSS Module 本身的设计很好的分离了 CSS 的静态和动态部分，因此被选作了 GojiJS 的默认 CSS 打包方案。

# CSS-in-JS

随着技术的发展，很多新的 CSS 打包方案被提出来，尤其是以“一切都是JavaScript”为指导思想的 CSS-in-JS 框架带来了新的开发视角和更高效的开发模式。

如上文所讲由于技术原因 GojiJS 对选择 CSS 打包方案存在很多限制，选择不恰当的方案可能会影响最终的性能体验。但这并不意味着 GojiJS 不能支持更多的框架，GojiJS 也在探索支持 CSS-in-JS 可行性。

目前我比较看好的是 [Linaria](https://github.com/callstack/linaria) ，与一般 CSS-in-JS 框架不同的是它的编译功能做的更加完善，可以自动识别 `style` 中的静态样式和动态样式，并进行分离。这种设计正好符合 GojiJS 和小程序的技术特点，开发者无需担心复杂的 `style` 属性会带来性能上的问题，也无需手动维护每一个 `class` 名字，在同一个 `.tsx` 文件中编写代码也要比同时修改两个独立的文件更加有整体性。

我认为理想的情况下，GojiJS 会提供几种常见的、可行的 CSS 打包方案供开发者选择，这些方案兼顾了前端开发的一般使用习惯和性能要求。出于对开发者负责的考虑，GojiJS 不会支持有着明显问题且尚未的问题的方案，以避免开发者踩中已知的坑。

**Comment by iheyunfei** [comment]
主要是大部分市面上 ui 库都是采用命名空间方案进行样式隔离，而 goji 只支持 css module 导致迁移这些 ui 库的流程变得复杂，本来只需要将模版更改成 jsx，但是现在同时需要将样式文件适配到 css module，特别是有些库都是使用 less 和 sass，它们编译到 css module 还有些坑。正常业务样式要进行隔离防污染很合理，但是组件库也强制绑定 css module 方案我是觉得不太好的，会导致额外的适配成本，也有些额外的小点，比如 css module 使得覆盖 ui 库组件样式变得麻烦。

### css module 作为唯一方案使得适配 ui 组件库的流程变得繁琐
- 市面上大部分 ui 库都采用的 命名空间 来隔离样式
- goji 默认把所有 css 文件都当作 css module 进行导入，没有逃逸手段
- 市面上 ui 库采用的 less sass 与 css module 的配合不是很好

### 样式隔离并不是强需求
我理解样式隔离是有必要的，但不应该作为强制选项，大部分项目并没有很强的隔离需求。其次是，css module 对于一个全新项目使用起来很好，但是对于迁移项目来讲，其实大部分工作只是发生在将模版改为 jsx，但是强制 css module 使得原有的样式文件必须要改写到 css module ，这其实是一个很大工作量，但只是简单一个配置项就可以解决的事情

### 支持直接引入 .wxss 文件
这里主要的考量是解耦 ui 库的编译逻辑和项目的编译逻辑，即使我现在适配了一个 ui 库，使用的 css-module 方案 ，但ui 组件还是会走开发者创建项目的 webpack loader，如果开发者通过修改 `goji.config.js` 中的 `configureWebpack()` 选择禁用掉 css module，就很容易出现样式污染的问题。

### 解决方案
我是觉得最好应该默认关闭 css module，把所有引入的 css 文件都只是简单做编译到 wxss 的逻辑，并暴露出对 css-module 的配置项，让开发者选择是否开启 css module，并选择使用什么样的模式。

其次是，对于  goji 选择相应的解决方案时，最好保留最原始最原生的解决方案，它可能使用起来很复杂很麻烦，但是第三方开发者很容易在其上面封装出适合自己的解决方案。
