### ISSUE TITLE
Native WeChat Mini-Program Components (Video, Progress, etc.) Unusable

### ISSUE THREAD

**Issue by Ziyu-Chen** [airbnb/goji-js#50]
Hi! I just noticed that I can't use several native WeChat mini-program components (such as Video and Progress) in my Goji.js project. It is imperative that I can use at least the Video component in my project. I noticed that many components in the factoryComponents.ts file do not have any props in addition to UnknownProps. Is it an intentional design to accommodate cross-platform performance? If so, is there any workaround for adding Video components to my Goji.js project? (I probably have to rewrite the entire project using Taro if there's no way to use Video components in my project.) Thank you in advance!
![Screen Shot 2020-12-11 at 2 54 35 PM](https://user-images.githubusercontent.com/47688464/101873043-3b9ffe00-3bc1-11eb-9684-e4100109ae30.png)

**Comment by Ziyu-Chen** [comment]
I just noticed that I can still use these components after several experiments. It's just that there will be "no such attribute" errors in my IDE. Problem solved... Sorry for all the fuss!

**Comment by Ziyu-Chen** [comment]
But it would be nice if you could complete the props lists for those native WeChat mini-program components that don't have any props in their types other than the UnknownProps. (If it would't undermine Goji's cross-platform performance.) Thank you again for this great framework. It indeed made my work easier!

**Comment by malash** [comment]
Hi @Ziyu-Chen Thank you for your advice. I'v created a PR to fix type check issue. https://github.com/airbnb/goji-js/pull/51
